### ISSUE TITLE
Reducing overall image size for self-contained EXASOL docker-db

### ISSUE THREAD

**Issue by wipatrick** [EXASOL/docker-db#10]
As of now, ```centos:6``` is used as the base image for the self-contained Docker image. However, this leads to a significant bigger EXASOL image (approx. +700MB). Some quick tests showed, that there are a couple of things that need to be refactored (e.g. in the submethod calls of ```exainit.py```) to get it working on Linux ```alpine``` base image.

On the other hand, looking at the the EXASuite directory, it shows that a lion's share of the overall  size is due to the ```EXARuntime``` folder.

```sh
[root@n11 EXASuite-6]# du -sh *
2.3M	3rd-party
528M	EXAClusterOS-6.0.1
1.6G	EXARuntime-6.0.1
156M	EXASolution-6.0.1
```

Can this further be reduced?

**Comment by ooke** [comment]
We have plans to reduce EXARuntime size, but please do not expect it in the next few months. Migration from CentOS to other base image is not planned, because all our products are supported only on CentOS for now. The EXARuntime refactoring will be released in future for all our products and it is not docker specific.
