### ISSUE TITLE
Creating Docker image using EXASOL docker - Issue

### ISSUE THREAD

**Issue by bhasamp** [EXASOL/docker-db#13]
Dear Team,

While creating docker image using docker file we are pulling exasol docker image from repository and issuing .exadt commands to create cluster. 

All commands are executing successfully, but when we validate cluster initialization using this command (./exadt ps MyCluster) we are getting the status as Exited and Exposed ports with null. 

Kindly please help us on the same.

Thanks,
Bhaskar

**Comment by exajuk** [comment]
Hi!

 We need more information in order to be able to investigate. Please execute the following command and attach the generated archive:

`exadt collect-info MyCluster`

Then execute `docker logs <Containername>` after the container exited and copy the output into this issue. 

Also take a look at the 'Reporting bugs' section in the README for how to provide further useful debugging information.

**Comment by bhasamp** [comment]
Thanks for the detailed information.  Please find the attached requested files for debugging

Output:

./exadt ps MyCluster

************************************************************************************************************
NODE ID   STATUS                      IMAGE VERSION   NAME   CONTAINER ID   CONTAINER NAME   EXPOSED PORTS
 11        Exited (1) 23 seconds ago   6.0.6-d1        n11    e54acddca728   MyCluster_11               
*************************************************************************************************************

docker logs e54acddca728
Traceback (most recent call last):
  File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.6/libexec/exainit.py", line 11, in <module>
    from exainit.config import config
  File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.6/exainit/config.py", line 20, in <module>
    exaconf = EXAConf(None, True)
  File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.6/devel/docker/libexadt/EXAConf.py", line 100, in __init__
    raise EXAConfError("root directory '%s' does not exist (or is a file)!" % self.root)
libexadt.EXAConf.EXAConfError: "ERROR::EXAConf: root directory '/exa/etc' does not exist (or is a file)!

[exasol_docker_info.zip](https://github.com/EXASOL/docker-db/files/1699401/exasol_docker_info.zip)

.

**Comment by bhasamp** [comment]
* We had build docker container using dockerfile
* Ran the docker image using following command
docker run -ti --rm -v /var/run/docker.sock:/var/run/docker.sock  docker_exasol sh
* We are executing the .exadt commands inside docker container image. 
* creation of cluster and starting is successful but when we investigate the cluster it is saying status as existed.

**Comment by exajuk** [comment]
OK, so you are trying to create an EXASOL Docker cluster from **within** another EXASOL Docker container? May I ask why you are doing that? Anyway, the error itself is pretty clear:

`"ERROR::EXAConf: root directory '/exa/etc' does not exist (or is a file)!`

It means that the volume that is mounted at `/exa/` in each container (by `exadt`) does not exist (or is empty). The path `/root/MyCluster/n11/` is created by `exadt` and used as the source for that volume. However, since you executed the `exadt` commands only within the first container, that path does not exist on the host and can therefore not be mounted into the containers created by `exadt`.

You can probably fix that by manually mounting `/root/MyCluster` into the first container and then execute the `exadt` commands with that mounted volume as the root directory for your cluster, e. g.:

`docker run -ti --rm -v /root/MyCluster/:/root/MyCluster/ -v /var/run/docker.sock:/var/run/docker.sock docker_exasol sh`

and then (within the first container)

`exadt create-cluster -r /root/MyCluster/ MyCluster`

You need a persistent volume on the host anyway, if you don't want to loose your data when shutting down the container.

If all you need is a single container for quick testing, you can also create an EXASOL container directly with `docker run` (see the 'Creating a stand-alone EXASOL container' section in the README).

**Comment by bhasamp** [comment]
Thanks for the detailed solution!  We had used single container option for quick testing and it is working as expected.
