### ISSUE TITLE
Not sure if docker 7.0 image is working

### ISSUE THREAD

**Issue by wildraid** [exasol/docker-db#54]
Hello,

I've tried to test 7.0 image with travis, but failed. 6.2 and 6.1 branches do not have this problem.

Logs: https://travis-ci.org/github/badoo/pyexasol/jobs/725981404

Error is simple:

```
Could not connect to Exasol: [Errno 104] Connection reset by peer
```

Maybe the startup time just got much slower than before.

Thank you.

**Comment by wildraid** [comment]
Full build logs: https://travis-ci.org/github/badoo/pyexasol/builds/725981395

**Comment by moben** [comment]
Hi,

the port for the default database in the image changed in 7.0 to be in line with the default port in Exaoperation based deployments.

It's now `8563` instead of `8888` inside the image.

I think you'll have to change the port forwarding in your `docker run` invocation from `-p 127.0.0.1:8563:8888` to `-p 127.0.0.1:8563:8563`. We updated the docs in this repository I think, but only for the 7.0 branch which is not yet set as the default in github, I'll look into that.

Let me know if it works for you with this change.

And thanks for adding 7.0 to your tests so quickly.

**Comment by wildraid** [comment]
Yes, it works! Perfect, thank you.
